kind: pipeline
name: react-nginx

steps:
- name: test
  image: node:14-alpine
  commands:
  - ls -al
  - cd react-nginx
  - yarn install
  - yarn test
  when:
    branch:
    - react-nginx

- name: build docker image
  image: docker:latest
  volumes:
    - name: docker_sock
      path: /var/run/docker.sock
  commands:
    - echo '192.168.86.40 unraid registry.unraid' | tee -a /etc/hosts
    - mkdir /etc/docker
    # - echo "{"insecure-registries":["registry.unraid.33294"]}" >> /etc/docker/daemon.json
    # - touch /etc/docker/daemon.json
    # - echo "{ \"insecure-registries\": [\"registry.unraid.33294\"] }" | tee -a /etc/docker/daemon.json
    # - systemctl status docker
    # - service docker restart
    # - docker system info
    - cd react-nginx
    - docker build --no-cache -t registry.unraid:33294/test/react-nginx:latest -f Dockerfile .
    - docker push registry.unraid:33294/test/react-nginx:latest

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock

# ---
# kind: pipeline
# name: test-on-arm64

# platform:
#   arch: arm64

# steps:
# - name: test
#   image: node
#   commands:
#   - npm install
#   - npm test