---
kind: pipeline
name: react-nginx

steps:
- name: test
  image: node:14-alpine
  commands:
  - npm install
  - npm test

---
# kind: pipeline
# name: test-on-arm64

# platform:
#   arch: arm64

# steps:
# - name: test
#   image: node
#   commands:
#   - npm install
#   - npm test