---
- name: drone info
  command: drone info

# - name: kube info
#   command: kubectl get nodes

- name: cleanup repo settings first
  command: drone secret rm {{repo_user}}/{{git_repo}} --name {{item.name}}
  loop:
    - {name: docker_user, data: "{{docker_user}}" }
    - {name: docker_pass, data: "{{docker_pass}}" }
    - {name: k8s_server, data: "{{k8s_server}}" }
    - {name: k8s_cert, data: "{{k8s_cert}}" }
    - {name: k8s_token, data: "{{k8s_token}}" }
    - {name: pipeline_notifier, data: "{{pipeline_notifier}}" }
  ignore_errors: yes

- name: push repo settings
  command: drone secret add {{repo_user}}/{{git_repo}} --name {{item.name}} --data {{item.data}}
  loop:
    - {name: docker_user, data: "{{docker_user}}" }
    - {name: docker_pass, data: "{{docker_pass}}" }
    - {name: k8s_server, data: "{{k8s_server}}" }
    - {name: k8s_cert, data: "{{k8s_cert}}" }
    - {name: k8s_token, data: "{{k8s_token}}" }
    - {name: pipeline_notifier, data: "{{pipeline_notifier}}" }