---
- hosts: localhost
  # gather_facts: yes
  # become: yes
  roles:
    - role: drone

# - hosts: kubes
#   gather_facts: yes
#   become: yes
#   roles:
#     - {role: k3d/master, tags: 'k3d'}
#     - {role: k3d/helms, tags: 'helms'}